-- 방문 로그 테스트 데이터 삽입
-- 다양한 날짜 범위의 방문 로그를 생성하여 통계 기능 테스트

-- 최근 데이터 (오늘, 어제)
INSERT INTO visit_log (user_id, center_id, created_at) VALUES
-- 오늘 방문 (3건)
(1, 2, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
(2, 2, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
(3, 2, DATE_SUB(NOW(), INTERVAL 1 HOUR)),

-- 어제 방문 (5건)
(1, 2, DATE_SUB(NOW(), INTERVAL 1 DAY) + INTERVAL 10 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 1 DAY) + INTERVAL 14 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 1 DAY) + INTERVAL 18 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 1 DAY) + INTERVAL 20 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 1 DAY) + INTERVAL 22 HOUR),

-- 이번 주 방문 (월요일부터)
(1, 2, DATE_SUB(NOW(), INTERVAL 2 DAY) + INTERVAL 12 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 2 DAY) + INTERVAL 15 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 3 DAY) + INTERVAL 11 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 3 DAY) + INTERVAL 16 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 4 DAY) + INTERVAL 13 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 4 DAY) + INTERVAL 19 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 5 DAY) + INTERVAL 14 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 5 DAY) + INTERVAL 17 HOUR),

-- 이번 달 방문 (2주 전부터)
(1, 2, DATE_SUB(NOW(), INTERVAL 7 DAY) + INTERVAL 10 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 7 DAY) + INTERVAL 14 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 8 DAY) + INTERVAL 11 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 8 DAY) + INTERVAL 16 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 9 DAY) + INTERVAL 13 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 9 DAY) + INTERVAL 19 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 10 DAY) + INTERVAL 12 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 10 DAY) + INTERVAL 15 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 11 DAY) + INTERVAL 14 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 11 DAY) + INTERVAL 18 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 12 DAY) + INTERVAL 10 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 12 DAY) + INTERVAL 16 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 13 DAY) + INTERVAL 13 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 13 DAY) + INTERVAL 17 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 14 DAY) + INTERVAL 11 HOUR),

-- 지난 달 방문 데이터
(1, 2, DATE_SUB(NOW(), INTERVAL 35 DAY) + INTERVAL 10 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 35 DAY) + INTERVAL 14 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 36 DAY) + INTERVAL 11 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 36 DAY) + INTERVAL 16 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 37 DAY) + INTERVAL 13 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 37 DAY) + INTERVAL 19 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 38 DAY) + INTERVAL 12 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 38 DAY) + INTERVAL 15 HOUR),

-- 볼링장별 다양한 방문 패턴
-- 볼링장 2에 집중된 방문
(1, 2, DATE_SUB(NOW(), INTERVAL 6 DAY) + INTERVAL 12 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 6 DAY) + INTERVAL 18 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 7 DAY) + INTERVAL 14 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 8 DAY) + INTERVAL 16 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 9 DAY) + INTERVAL 13 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 10 DAY) + INTERVAL 15 HOUR),

-- 추가 방문 데이터
(2, 2, DATE_SUB(NOW(), INTERVAL 6 DAY) + INTERVAL 10 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 6 DAY) + INTERVAL 19 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 7 DAY) + INTERVAL 11 HOUR),
(2, 2, DATE_SUB(NOW(), INTERVAL 8 DAY) + INTERVAL 17 HOUR),
(3, 2, DATE_SUB(NOW(), INTERVAL 9 DAY) + INTERVAL 12 HOUR),
(1, 2, DATE_SUB(NOW(), INTERVAL 10 DAY) + INTERVAL 14 HOUR);

